<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Tool;
use App\Models\Item;

class MasterDataSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Setup Data Akun Default
        if (User::count() == 0) {
            User::create([
                'nama_lengkap' => 'Admin IPWIJA',
                'email' => 'admin@ipwija.ac.id',
                'password' => bcrypt('password'),
                'role' => 'admin',
                'no_whatsapp' => '081234567890',
            ]);
        }

        // 2. Data Master Alat (tools)
        $tools = [
            ['kode' => 'TL-MED-0006', 'nama' => '½ kocher', 'kategori' => 'Alat Medis', 'stok' => 3],
            ['kode' => 'TL-MED-0009', 'nama' => 'Tangga', 'kategori' => 'Fasilitas Lab', 'stok' => 2],
            ['kode' => 'TL-MED-0013', 'nama' => 'Epis', 'kategori' => 'Alat Medis', 'stok' => 3],
            ['kode' => 'TL-MED-0020', 'nama' => 'Katetermetal', 'kategori' => 'Alat Medis', 'stok' => 3],
            ['kode' => 'TL-MED-0022', 'nama' => 'Mikroskop', 'kategori' => 'Alat Laboratorium', 'stok' => 15],
            ['kode' => 'TL-MED-0030', 'nama' => 'Stetoskop', 'kategori' => 'Fasilitas Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0031', 'nama' => 'Phantom penis', 'kategori' => 'Fasilitas Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0036', 'nama' => 'Tabung reaksi besar', 'kategori' => 'Alat Laboratorium', 'stok' => 67],
            ['kode' => 'TL-MED-0038', 'nama' => 'Phantom penis kecil', 'kategori' => 'Fasilitas Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0041', 'nama' => 'Needle holder ifuder', 'kategori' => 'Alat Medis', 'stok' => 4],
            ['kode' => 'TL-MED-0043', 'nama' => 'Tabung reaksi kecil', 'kategori' => 'Alat Laboratorium', 'stok' => 25],
            ['kode' => 'TL-MED-0045', 'nama' => 'Phantom vagina', 'kategori' => 'Fasilitas Medis', 'stok' => 2],
            ['kode' => 'TL-MED-0048', 'nama' => 'scaper', 'kategori' => 'Alat Medis', 'stok' => 3],
            ['kode' => 'TL-MED-0050', 'nama' => 'Penjepit tabung', 'kategori' => 'Alat Laboratorium', 'stok' => 7],
            ['kode' => 'TL-MED-0052', 'nama' => 'Phantom plasenta', 'kategori' => 'Fasilitas Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0055', 'nama' => 'Oligator', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0057', 'nama' => 'Pipet plastic', 'kategori' => 'Alat Laboratorium', 'stok' => 3],
            ['kode' => 'TL-MED-0059', 'nama' => 'Phantom bayi kecil', 'kategori' => 'Fasilitas Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0062', 'nama' => 'opa', 'kategori' => 'Alat Medis', 'stok' => 3],
            ['kode' => 'TL-MED-0063', 'nama' => 'Korset', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0064', 'nama' => 'Pipet kaca', 'kategori' => 'Alat Laboratorium', 'stok' => 67],
            ['kode' => 'TL-MED-0065', 'nama' => 'Patung tangan', 'kategori' => 'Fasilitas Medis', 'stok' => 2],
            ['kode' => 'TL-MED-0068', 'nama' => 'Gunting tali pusat', 'kategori' => 'Alat Medis', 'stok' => 2],
            ['kode' => 'TL-MED-0070', 'nama' => 'Beaker glass 500 ML', 'kategori' => 'Alat Laboratorium', 'stok' => 4],
            ['kode' => 'TL-MED-0073', 'nama' => 'tenakulum', 'kategori' => 'Alat Medis', 'stok' => 2],
            ['kode' => 'TL-MED-0075', 'nama' => 'Beaker glass 250 ML', 'kategori' => 'Alat Laboratorium', 'stok' => 3],
            ['kode' => 'TL-MED-0078', 'nama' => 'Sonde', 'kategori' => 'Alat Medis', 'stok' => 2],
            ['kode' => 'TL-MED-0080', 'nama' => 'Beaker glass 100 ML', 'kategori' => 'Alat Laboratorium', 'stok' => 4],
            ['kode' => 'TL-MED-0083', 'nama' => 'Panser laem', 'kategori' => 'Alat Medis', 'stok' => 2],
            ['kode' => 'TL-MED-0085', 'nama' => 'Kaca glass 50 ML', 'kategori' => 'Alat Laboratorium', 'stok' => 6],
            ['kode' => 'TL-MED-0088', 'nama' => 'Klem pen bengkok besar', 'kategori' => 'Alat Medis', 'stok' => 3],
            ['kode' => 'TL-MED-0090', 'nama' => 'Kaca glass 250 ML', 'kategori' => 'Alat Laboratorium', 'stok' => 6],
            ['kode' => 'TL-MED-0091', 'nama' => 'Gelas huknah', 'kategori' => 'Fasilitas Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0093', 'nama' => 'Klem pen bengkok kecil', 'kategori' => 'Alat Medis', 'stok' => 2],
            ['kode' => 'TL-MED-0094', 'nama' => 'Baskom Klorin 6', 'kategori' => 'Alat Medis', 'stok' => 12],
            ['kode' => 'TL-MED-0095', 'nama' => 'Kaca glass 10 ML', 'kategori' => 'Alat Laboratorium', 'stok' => 4],
            ['kode' => 'TL-MED-0098', 'nama' => 'Korentang + tempat', 'kategori' => 'Alat Medis', 'stok' => 4],
            ['kode' => 'TL-MED-0099', 'nama' => 'Baskom DTT 6', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0100', 'nama' => 'Corong glass', 'kategori' => 'Alat Laboratorium', 'stok' => 5],
            ['kode' => 'TL-MED-0103', 'nama' => 'Set implan', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0104', 'nama' => 'Bak mandi bayi', 'kategori' => 'Alat Medis', 'stok' => 2],
            ['kode' => 'TL-MED-0105', 'nama' => 'Gelas ukur 50 ML', 'kategori' => 'Alat Laboratorium', 'stok' => 4],
            ['kode' => 'TL-MED-0108', 'nama' => 'Klem tali pusat', 'kategori' => 'Alat Medis', 'stok' => 8],
            ['kode' => 'TL-MED-0110', 'nama' => 'Gelas ukur 25 ML', 'kategori' => 'Alat Laboratorium', 'stok' => 3],
            ['kode' => 'TL-MED-0113', 'nama' => 'IUD remufel hook', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0114', 'nama' => 'Gelas', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0115', 'nama' => 'Gelas ukur 10 ML', 'kategori' => 'Alat Laboratorium', 'stok' => 4],
            ['kode' => 'TL-MED-0118', 'nama' => 'Gunting benang biasa besar', 'kategori' => 'Alat Medis', 'stok' => 2],
            ['kode' => 'TL-MED-0119', 'nama' => 'Phantom bayi', 'kategori' => 'Alat Medis', 'stok' => 5],
            ['kode' => 'TL-MED-0120', 'nama' => 'Lampu spirtus', 'kategori' => 'Alat Laboratorium', 'stok' => 4],
            ['kode' => 'TL-MED-0123', 'nama' => 'Gunting benang biasa kecil', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0124', 'nama' => 'Timbangan bayi', 'kategori' => 'Alat Medis', 'stok' => 2],
            ['kode' => 'TL-MED-0128', 'nama' => 'Gunting UP hecting', 'kategori' => 'Alat Medis', 'stok' => 2],
            ['kode' => 'TL-MED-0129', 'nama' => 'Timbangan dewasa', 'kategori' => 'Alat Medis', 'stok' => 5],
            ['kode' => 'TL-MED-0130', 'nama' => 'Cawan dan alat penumbuk', 'kategori' => 'Alat Laboratorium', 'stok' => 11],
            ['kode' => 'TL-MED-0131', 'nama' => 'Phantom Hecting', 'kategori' => 'Fasilitas Medis', 'stok' => 2],
            ['kode' => 'TL-MED-0133', 'nama' => 'Vulkosa steril', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0135', 'nama' => 'Preparat set', 'kategori' => 'Alat Laboratorium', 'stok' => 1],
            ['kode' => 'TL-MED-0136', 'nama' => 'Phantom untuk dada bayi', 'kategori' => 'Fasilitas Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0138', 'nama' => 'Laken', 'kategori' => 'Alat Medis', 'stok' => 6],
            ['kode' => 'TL-MED-0139', 'nama' => 'BH payudara', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0140', 'nama' => 'Kaki tiga', 'kategori' => 'Alat Laboratorium', 'stok' => 9],
            ['kode' => 'TL-MED-0143', 'nama' => 'Stik laken', 'kategori' => 'Alat Medis', 'stok' => 6],
            ['kode' => 'TL-MED-0144', 'nama' => 'Topi bayi', 'kategori' => 'Alat Medis', 'stok' => 7],
            ['kode' => 'TL-MED-0145', 'nama' => 'Kaca pembesar', 'kategori' => 'Alat Laboratorium', 'stok' => 6],
            ['kode' => 'TL-MED-0150', 'nama' => 'Cermin miscrosop', 'kategori' => 'Alat Laboratorium', 'stok' => 15],
            ['kode' => 'TL-MED-0151', 'nama' => 'Phantom panggul', 'kategori' => 'Fasilitas Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0154', 'nama' => 'Sarung tangan bayi', 'kategori' => 'Alat Medis', 'stok' => 6],
            ['kode' => 'TL-MED-0155', 'nama' => 'Lancing device', 'kategori' => 'Alat Laboratorium', 'stok' => 1],
            ['kode' => 'TL-MED-0156', 'nama' => 'Phantom NGT', 'kategori' => 'Fasilitas Medis', 'stok' => 2],
            ['kode' => 'TL-MED-0159', 'nama' => 'Microsope slides', 'kategori' => 'Alat Laboratorium', 'stok' => 1],
            ['kode' => 'TL-MED-0161', 'nama' => 'Gelas kaca kecil', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0163', 'nama' => 'Surgical blades', 'kategori' => 'Alat Laboratorium', 'stok' => 1],
            ['kode' => 'TL-MED-0167', 'nama' => 'PH', 'kategori' => 'Alat Laboratorium', 'stok' => 1],
            ['kode' => 'TL-MED-0171', 'nama' => 'Batang pengaduk', 'kategori' => 'Alat Laboratorium', 'stok' => 7],
            ['kode' => 'TL-MED-0174', 'nama' => 'Washlap', 'kategori' => 'Alat Medis', 'stok' => 14],
            ['kode' => 'TL-MED-0175', 'nama' => 'Buret', 'kategori' => 'Alat Laboratorium', 'stok' => 3],
            ['kode' => 'TL-MED-0179', 'nama' => 'Tabung reaksi tutup', 'kategori' => 'Alat Laboratorium', 'stok' => 2],
            ['kode' => 'TL-MED-0185', 'nama' => 'Gurita ibu', 'kategori' => 'Alat Medis', 'stok' => 2],
            ['kode' => 'TL-MED-0187', 'nama' => 'Mitella', 'kategori' => 'Alat Medis', 'stok' => 5],
            ['kode' => 'TL-MED-0192', 'nama' => 'Boneka payudara', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0194', 'nama' => 'Semprotan DTT', 'kategori' => 'Alat Medis', 'stok' => 4],
            ['kode' => 'TL-MED-0196', 'nama' => 'Suhu tembak', 'kategori' => 'Alat Medis', 'stok' => 2],
            ['kode' => 'TL-MED-0198', 'nama' => 'Suhu digital', 'kategori' => 'Alat Medis', 'stok' => 5],
            ['kode' => 'TL-MED-0202', 'nama' => 'Metline', 'kategori' => 'Alat Medis', 'stok' => 5],
            ['kode' => 'TL-MED-0204', 'nama' => 'Penlight', 'kategori' => 'Alat Medis', 'stok' => 5],
            ['kode' => 'TL-MED-0206', 'nama' => 'Patela', 'kategori' => 'Alat Medis', 'stok' => 5],
            ['kode' => 'TL-MED-0208', 'nama' => 'Tourniqwet', 'kategori' => 'Alat Medis', 'stok' => 4],
            ['kode' => 'TL-MED-0209', 'nama' => 'Dili', 'kategori' => 'Alat Medis', 'stok' => 3],
            ['kode' => 'TL-MED-0211', 'nama' => 'Senter kuning', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0213', 'nama' => 'Pitalila', 'kategori' => 'Alat Medis', 'stok' => 5],
            ['kode' => 'TL-MED-0215', 'nama' => 'Lancing', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0217', 'nama' => 'Linec', 'kategori' => 'Alat Medis', 'stok' => 4],
            ['kode' => 'TL-MED-0221', 'nama' => 'Pengukur TB', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0223', 'nama' => 'Dopler', 'kategori' => 'Alat Medis', 'stok' => 4],
            ['kode' => 'TL-MED-0225', 'nama' => 'Resuscitation', 'kategori' => 'Alat Medis', 'stok' => 2],
            ['kode' => 'TL-MED-0227', 'nama' => 'Tensi Digital', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0229', 'nama' => 'Buku buta warna', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0231', 'nama' => 'Softtex', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0233', 'nama' => 'Kacamata Google', 'kategori' => 'Alat Medis', 'stok' => 4],
            ['kode' => 'TL-MED-0235', 'nama' => 'GYM ball', 'kategori' => 'Alat Medis', 'stok' => 2],
            ['kode' => 'TL-MED-0239', 'nama' => 'Kom trolly', 'kategori' => 'Alat Medis', 'stok' => 5],
            ['kode' => 'TL-MED-0241', 'nama' => 'Phantom perut INC', 'kategori' => 'Alat Medis', 'stok' => 3],
            ['kode' => 'TL-MED-0243', 'nama' => 'Phantom perut KB', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0245', 'nama' => 'Phantom tangan', 'kategori' => 'Alat Medis', 'stok' => 2],
            ['kode' => 'TL-MED-0247', 'nama' => 'Plasenta', 'kategori' => 'Alat Medis', 'stok' => 4],
            ['kode' => 'TL-MED-0249', 'nama' => 'Trolly bayi', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0255', 'nama' => 'Phantom akfeksia', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0257', 'nama' => 'Phantom ibu hamil', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0261', 'nama' => 'Lampu sorot', 'kategori' => 'Alat Medis', 'stok' => 4],
            ['kode' => 'TL-MED-0263', 'nama' => 'Oksigen', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0265', 'nama' => 'SDIDTK', 'kategori' => 'Alat Medis', 'stok' => 2],
            ['kode' => 'TL-MED-0267', 'nama' => 'Tiang infus', 'kategori' => 'Alat Medis', 'stok' => 3],
            ['kode' => 'TL-MED-0271', 'nama' => 'Linen kotor', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0273', 'nama' => 'Tempat plasenta', 'kategori' => 'Alat Medis', 'stok' => 2],
            ['kode' => 'TL-MED-0276', 'nama' => 'Accarbic acid', 'kategori' => 'BHP Medis', 'stok' => 3],
            ['kode' => 'TL-MED-0279', 'nama' => 'Bengkok', 'kategori' => 'Alat Medis', 'stok' => 6],
            ['kode' => 'TL-MED-0281', 'nama' => 'Kom kecil', 'kategori' => 'Alat Medis', 'stok' => 4],
            ['kode' => 'TL-MED-0283', 'nama' => 'Kom kecil banget', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0285', 'nama' => 'Baki sedang', 'kategori' => 'Alat Medis', 'stok' => 7],
            ['kode' => 'TL-MED-0287', 'nama' => 'Tutup baki sedang', 'kategori' => 'Alat Medis', 'stok' => 7],
            ['kode' => 'TL-MED-0289', 'nama' => 'Baki besar', 'kategori' => 'Alat Medis', 'stok' => 4],
            ['kode' => 'TL-MED-0291', 'nama' => 'Tutup baki besar', 'kategori' => 'Alat Medis', 'stok' => 4],
            ['kode' => 'TL-MED-0293', 'nama' => 'Baki kecil', 'kategori' => 'Alat Medis', 'stok' => 5],
            ['kode' => 'TL-MED-0295', 'nama' => 'Tutup baki kecil', 'kategori' => 'Alat Medis', 'stok' => 5],
            ['kode' => 'TL-MED-0299', 'nama' => 'Gunting epis', 'kategori' => 'Alat Medis', 'stok' => 3],
            ['kode' => 'TL-MED-0301', 'nama' => 'Kateter metal', 'kategori' => 'Alat Medis', 'stok' => 3],
            ['kode' => 'TL-MED-0308', 'nama' => 'Sekapel', 'kategori' => 'Alat Medis', 'stok' => 3],
            ['kode' => 'TL-MED-0310', 'nama' => 'Allgator', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0316', 'nama' => 'Tenaculum', 'kategori' => 'Alat Medis', 'stok' => 2],
            ['kode' => 'TL-MED-0318', 'nama' => 'Sonaet', 'kategori' => 'Alat Medis', 'stok' => 2],
            ['kode' => 'TL-MED-0328', 'nama' => 'Set Impan', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0334', 'nama' => 'Gunting benang besar', 'kategori' => 'Alat Medis', 'stok' => 2],
            ['kode' => 'TL-MED-0336', 'nama' => 'Gunting bennag kecil', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'TL-MED-0340', 'nama' => 'Kukusan steril', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'BB400', 'nama' => 'BreadBoard 400 point', 'kategori' => 'Microcontroller', 'stok' => 10],
            ['kode' => 'SHC', 'nama' => 'Sensor Jarak (Ultra sonicHCSR 04)', 'kategori' => 'Fasilitas Lab', 'stok' => 10],
            ['kode' => 'TL-IT-0377', 'nama' => 'Sensor cahaya ( PHoto Resistor/ LDR)', 'kategori' => 'Komponen Elektronik', 'stok' => 10],
            ['kode' => 'TL-IT-0378', 'nama' => 'Sensor Suhu dan kelembapan (DHT 11)', 'kategori' => 'Microcontroller', 'stok' => 10],
            ['kode' => 'LCD1602', 'nama' => 'LCD 1602 (16x2)', 'kategori' => 'Microcontroller', 'stok' => 10],
            ['kode' => 'RLY', 'nama' => 'Modul Relay 1 Chanel', 'kategori' => 'Microcontroller', 'stok' => 10],
            ['kode' => 'UNO.PB', 'nama' => 'Arduino Uno R3 Tipe SMD/ DIP', 'kategori' => 'Microcontroller', 'stok' => 10],
            ['kode' => 'SG90', 'nama' => 'Motor servo (SG900)', 'kategori' => 'Microcontroller', 'stok' => 10],
            ['kode' => 'TL-IT-0386', 'nama' => 'Crimping tool', 'kategori' => 'Komponen Elektronik', 'stok' => 10],
            ['kode' => 'TL-IT-0387', 'nama' => 'tp-link Wifi Range Extender 300Mbps 2.4Ghz', 'kategori' => 'Alat Jaringan', 'stok' => 1],
            ['kode' => 'TL-IT-0388', 'nama' => 'Network Cable Tester', 'kategori' => 'Alat Jaringan', 'stok' => 10],
            ['kode' => 'TL-IT-0389', 'nama' => '⁠2pcs Tenda 500m Outdoor Point to Point CPE', 'kategori' => 'Alat Jaringan', 'stok' => 1],
            ['kode' => 'TL-IT-0390', 'nama' => 'Set Crimping tool', 'kategori' => 'Komponen Elektronik', 'stok' => 2],
            ['kode' => 'TL-IT-0391', 'nama' => 'Adaptor Rasberry5', 'kategori' => 'Alat Jaringan', 'stok' => 1],
            ['kode' => 'TL-IT-0392', 'nama' => 'Rasberry Pi', 'kategori' => 'Alat Jaringan', 'stok' => 1],
            ['kode' => 'TL-IT-0395', 'nama' => 'Obeng 24 in 1', 'kategori' => 'Alat Jaringan', 'stok' => 1],
            ['kode' => 'CARARC', 'nama' => 'Smart Car Acrylic Chassis', 'kategori' => 'Robotik', 'stok' => 10],
            ['kode' => 'BAN', 'nama' => 'Wheels', 'kategori' => 'Robotik', 'stok' => 10],
            ['kode' => 'UNO.PB-DUP', 'nama' => 'Arduino Uno R3 Tipe SMD/ DIP + pin header', 'kategori' => 'Komponen Elektronik', 'stok' => 10],
            ['kode' => 'SSHD', 'nama' => 'sensor shield v5.0', 'kategori' => 'Robotik', 'stok' => 10],
            ['kode' => 'MRDC', 'nama' => '2 Motor DC', 'kategori' => 'Robotik', 'stok' => 10],
            ['kode' => 'TL-IT-0405', 'nama' => 'Swivel Wheel', 'kategori' => 'Robotik', 'stok' => 10],
            ['kode' => 'TL-IT-0408', 'nama' => 'L298N driver', 'kategori' => 'Robotik', 'stok' => 10],
            ['kode' => 'OB21', 'nama' => 'Obeng', 'kategori' => 'Robotik', 'stok' => 10],
            ['kode' => 'BPAK', 'nama' => 'Base Plate Arm Kit', 'kategori' => 'Microcontroller', 'stok' => 1],
            ['kode' => 'MG90', 'nama' => 'Motor Servo MG90', 'kategori' => 'Microcontroller', 'stok' => 4],
            ['kode' => 'SAK', 'nama' => 'Shoulder', 'kategori' => 'Microcontroller', 'stok' => 1],
            ['kode' => 'EAK', 'nama' => 'Elbow', 'kategori' => 'Microcontroller', 'stok' => 1],
            ['kode' => 'TL-IT-0416', 'nama' => 'Arduino Nano + Shield', 'kategori' => 'Microcontroller', 'stok' => 1],
            ['kode' => 'BAK', 'nama' => 'Base', 'kategori' => 'Microcontroller', 'stok' => 1],
            ['kode' => 'OB1', 'nama' => 'Obeng Kembang', 'kategori' => 'Microcontroller', 'stok' => 1],
            ['kode' => 'TPC', 'nama' => 'USB Type C', 'kategori' => 'Microcontroller', 'stok' => 1],
            ['kode' => 'TL-IT-0420', 'nama' => 'Grip Left & Right', 'kategori' => 'Microcontroller', 'stok' => 1],
            ['kode' => 'LEDMM41', 'nama' => 'LED DOT Matrix Module 8x8 4 in 1', 'kategori' => 'Komponen Elektronik', 'stok' => 4],
            ['kode' => 'TMS', 'nama' => 'Timah Solder', 'kategori' => 'Komponen Elektronik', 'stok' => 4],
            ['kode' => 'DGMTR', 'nama' => 'Digital Multimeter', 'kategori' => 'Robotik', 'stok' => 4],
            ['kode' => 'DSPM4D', 'nama' => '4 Digit Display Module', 'kategori' => 'Robotik', 'stok' => 4],
            ['kode' => 'TL-IT-0432', 'nama' => '1 Set Kit ESP-32', 'kategori' => 'Robotik', 'stok' => 4],
            ['kode' => 'TL-IT-0433', 'nama' => 'Isi 1 Set Kit ESP-32', 'kategori' => 'Robotik', 'stok' => 1],
            ['kode' => 'ESP-32', 'nama' => 'ESP-32', 'kategori' => 'Robotik', 'stok' => 1],
            ['kode' => 'PIRA346', 'nama' => 'Sensor gerak PIR A346', 'kategori' => 'Fasilitas Lab', 'stok' => 1],
            ['kode' => 'SDH11', 'nama' => 'Sensor Suhu dan Kelembapan', 'kategori' => 'Robotik', 'stok' => 1],
            ['kode' => 'RLY2C', 'nama' => 'Modul Relay 2 Channel', 'kategori' => 'Robotik', 'stok' => 1],
            ['kode' => 'MSLDR', 'nama' => 'Modul Sensor Cahaya', 'kategori' => 'Robotik', 'stok' => 1],
            ['kode' => 'MSIFRM', 'nama' => 'Modul Sensor Inframerah', 'kategori' => 'Robotik', 'stok' => 1],
            ['kode' => 'BB800', 'nama' => 'BreadBoard 800 point', 'kategori' => 'Robotik', 'stok' => 1],
            ['kode' => 'TL-IT-0446', 'nama' => 'Tactile Push Button', 'kategori' => 'Robotik', 'stok' => 6],
            ['kode' => 'TL-IT-0450', 'nama' => 'Modul Expansion Shield Board ESP32', 'kategori' => 'Robotik', 'stok' => 4],
            ['kode' => 'TL-IT-0451', 'nama' => 'Modul Expansion Board ESP8266', 'kategori' => 'Robotik', 'stok' => 4],
            ['kode' => 'ESP8266', 'nama' => 'ESP8266', 'kategori' => 'Robotik', 'stok' => 4],
            ['kode' => 'LCMUT', 'nama' => 'LC Mini Ultrasonic Tester', 'kategori' => 'Robotik', 'stok' => 4],
            ['kode' => 'MQ2GS', 'nama' => 'Modul Sensor Gas', 'kategori' => 'Robotik', 'stok' => 4],
            ['kode' => 'RFID', 'nama' => 'RFID-RC255', 'kategori' => 'Robotik', 'stok' => 4],
            ['kode' => 'SWSNSR', 'nama' => 'Modul Sweep Hand Scan Sensor', 'kategori' => 'Robotik', 'stok' => 4],
            ['kode' => 'SKTM', 'nama' => 'Sakelar Toggle Mini', 'kategori' => 'Robotik', 'stok' => 4],
            ['kode' => 'HW006', 'nama' => 'Sensor Tracking Inframerah', 'kategori' => 'Robotik', 'stok' => 10],
            ['kode' => 'TTP223B', 'nama' => 'Modul Sensor Sentuh', 'kategori' => 'Robotik', 'stok' => 4],
            ['kode' => 'PCBHS', 'nama' => 'Ragum Pcb Pcb Ragum Pcb Holder Pcb Stand Series', 'kategori' => 'Alat Teknik', 'stok' => 4],
            ['kode' => 'FLX-SD', 'nama' => 'Flux Solder Solder Soldering Paste', 'kategori' => 'Komponen Elektronik', 'stok' => 4],
            ['kode' => 'MTRSLDR', 'nama' => 'Matras Solder', 'kategori' => 'Alat Teknik', 'stok' => 4],
        ];

        foreach ($tools as $t) {
            $lokasi = in_array($t['kategori'], ['Alat Laboratorium', 'Alat Medis', 'Fasilitas Medis', 'Instrumen Medis', 'Phantom']) 
                      ? 'Lab Kebidanan & Biomedis' 
                      : 'Lab Komputer & Robotik';

            Tool::create([
                'kode_alat' => $t['kode'],
                'nama_alat' => $t['nama'],
                'kategori' => $t['kategori'],
                'deskripsi' => 'Alat lab: ' . $t['nama'],
                'stok_total' => $t['stok'],
                'stok_tersedia' => $t['stok'],
                'status_alat' => 'Tersedia',
                'lokasi' => $lokasi,
            ]);
        }

        // 3. Data Master Barang (items)
        $items = [
            ['kode' => 'ITM-MED-0000', 'nama' => 'Sampiran/Gorden', 'kategori' => 'Fasilitas Lab', 'stok' => 19],
            ['kode' => 'ITM-MED-0001', 'nama' => 'Lemari', 'kategori' => 'Fasilitas Lab', 'stok' => 1],
            ['kode' => 'ITM-MED-0002', 'nama' => 'Kasur', 'kategori' => 'Fasilitas Lab', 'stok' => 3],
            ['kode' => 'ITM-MED-0003', 'nama' => 'Perlak besar', 'kategori' => 'Fasilitas Medis', 'stok' => 12],
            ['kode' => 'ITM-MED-0004', 'nama' => 'Bangku', 'kategori' => 'Fasilitas Medis', 'stok' => 17],
            ['kode' => 'ITM-MED-0005', 'nama' => 'Spuit 5ML', 'kategori' => 'BHP Medis', 'stok' => 19],
            ['kode' => 'ITM-MED-0007', 'nama' => 'Kain rainbow kecil', 'kategori' => 'Alat Medis', 'stok' => 12],
            ['kode' => 'ITM-MED-0008', 'nama' => 'Bangku meja', 'kategori' => 'Fasilitas Lab', 'stok' => 9],
            ['kode' => 'ITM-MED-0010', 'nama' => 'Perlak sedang', 'kategori' => 'Fasilitas Medis', 'stok' => 10],
            ['kode' => 'ITM-MED-0011', 'nama' => 'Meja', 'kategori' => 'Fasilitas Lab', 'stok' => 1],
            ['kode' => 'ITM-MED-0012', 'nama' => 'Spuit 3ML', 'kategori' => 'BHP Medis', 'stok' => 25],
            ['kode' => 'ITM-MED-0014', 'nama' => 'Kain Pembalut', 'kategori' => 'Alat Medis', 'stok' => 5],
            ['kode' => 'ITM-MED-0015', 'nama' => 'Kursi biru', 'kategori' => 'Fasilitas Lab', 'stok' => 12],
            ['kode' => 'ITM-MED-0016', 'nama' => 'Trolly', 'kategori' => 'Fasilitas Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0017', 'nama' => 'Perlak kecil', 'kategori' => 'Fasilitas Medis', 'stok' => 3],
            ['kode' => 'ITM-MED-0018', 'nama' => 'Papan tulis', 'kategori' => 'Fasilitas Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0019', 'nama' => 'Spuit 1ML', 'kategori' => 'BHP Medis', 'stok' => 13],
            ['kode' => 'ITM-MED-0021', 'nama' => 'Kain Jarik', 'kategori' => 'Alat Medis', 'stok' => 7],
            ['kode' => 'ITM-MED-0023', 'nama' => 'Tensi', 'kategori' => 'Fasilitas Medis', 'stok' => 2],
            ['kode' => 'ITM-MED-0024', 'nama' => 'Perlak super kecil', 'kategori' => 'Fasilitas Medis', 'stok' => 7],
            ['kode' => 'ITM-MED-0025', 'nama' => 'AC', 'kategori' => 'Fasilitas Medis', 'stok' => 2],
            ['kode' => 'ITM-MED-0026', 'nama' => 'Abocath', 'kategori' => 'BHP Medis', 'stok' => 2],
            ['kode' => 'ITM-MED-0027', 'nama' => 'Pinset anatomis', 'kategori' => 'Alat Medis', 'stok' => 4],
            ['kode' => 'ITM-MED-0028', 'nama' => 'Kain bedong', 'kategori' => 'Alat Medis', 'stok' => 9],
            ['kode' => 'ITM-MED-0032', 'nama' => 'Layar proyektor', 'kategori' => 'Fasilitas Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0033', 'nama' => 'Spuit 60ML', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0034', 'nama' => 'Pinset cirugis', 'kategori' => 'Alat Medis', 'stok' => 4],
            ['kode' => 'ITM-MED-0035', 'nama' => 'Handuk bayi', 'kategori' => 'Fasilitas Lab', 'stok' => 7],
            ['kode' => 'ITM-MED-0037', 'nama' => 'Sampiran', 'kategori' => 'Fasilitas Lab', 'stok' => 3],
            ['kode' => 'ITM-MED-0039', 'nama' => 'Kartu tes daya lihat', 'kategori' => 'Fasilitas Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0040', 'nama' => 'Spuit 5ML (Steril)', 'kategori' => 'BHP Medis', 'stok' => 5],
            ['kode' => 'ITM-MED-0042', 'nama' => 'Selimut rainbow', 'kategori' => 'Alat Medis', 'stok' => 7],
            ['kode' => 'ITM-MED-0044', 'nama' => 'Kursi', 'kategori' => 'Fasilitas Lab', 'stok' => 3],
            ['kode' => 'ITM-MED-0046', 'nama' => 'Lembar balik (Kelas ibu hamil, balita, dll)', 'kategori' => 'Fasilitas Medis', 'stok' => 13],
            ['kode' => 'ITM-MED-0047', 'nama' => 'Spuit 3ML (Steril)', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0049', 'nama' => 'Baju pasien', 'kategori' => 'Fasilitas Lab', 'stok' => 20],
            ['kode' => 'ITM-MED-0053', 'nama' => 'Poster', 'kategori' => 'Fasilitas Medis', 'stok' => 12],
            ['kode' => 'ITM-MED-0054', 'nama' => 'Abocath (Steril)', 'kategori' => 'BHP Medis', 'stok' => 2],
            ['kode' => 'ITM-MED-0056', 'nama' => 'Selimut bayi', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0060', 'nama' => 'Parto I', 'kategori' => 'Fasilitas Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0061', 'nama' => 'Spuit 0,1 ML', 'kategori' => 'BHP Medis', 'stok' => 2],
            ['kode' => 'ITM-MED-0066', 'nama' => 'Parto II', 'kategori' => 'Fasilitas Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0067', 'nama' => 'Spuit 0,05 ML', 'kategori' => 'BHP Medis', 'stok' => 2],
            ['kode' => 'ITM-MED-0069', 'nama' => 'Safety box', 'kategori' => 'Fasilitas Lab', 'stok' => 5],
            ['kode' => 'ITM-MED-0071', 'nama' => 'Patung Wanita', 'kategori' => 'Fasilitas Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0072', 'nama' => 'Spuit 0,3ML', 'kategori' => 'BHP Medis', 'stok' => 4],
            ['kode' => 'ITM-MED-0074', 'nama' => 'Celemek Kain : 2', 'kategori' => 'Fasilitas Lab', 'stok' => 4],
            ['kode' => 'ITM-MED-0076', 'nama' => 'Kasa', 'kategori' => 'Fasilitas Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0077', 'nama' => 'Spuit 0,5ML', 'kategori' => 'BHP Medis', 'stok' => 18],
            ['kode' => 'ITM-MED-0079', 'nama' => 'Plastik : 2', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0081', 'nama' => 'Spuit giliserin', 'kategori' => 'Fasilitas Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0084', 'nama' => 'Ember', 'kategori' => 'Fasilitas Lab', 'stok' => 5],
            ['kode' => 'ITM-MED-0086', 'nama' => 'Selang huknah', 'kategori' => 'Fasilitas Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0087', 'nama' => 'Needle 25G', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0089', 'nama' => 'Tong sampah', 'kategori' => 'Fasilitas Lab', 'stok' => 18],
            ['kode' => 'ITM-MED-0092', 'nama' => 'Needle 23G', 'kategori' => 'BHP Medis', 'stok' => 3],
            ['kode' => 'ITM-MED-0096', 'nama' => 'Stik huknah', 'kategori' => 'Fasilitas Medis', 'stok' => 2],
            ['kode' => 'ITM-MED-0097', 'nama' => 'Maxiflow dewasa', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0101', 'nama' => 'Toples kecil', 'kategori' => 'Fasilitas Medis', 'stok' => 2],
            ['kode' => 'ITM-MED-0102', 'nama' => 'Selang oksigen', 'kategori' => 'BHP Medis', 'stok' => 2],
            ['kode' => 'ITM-MED-0106', 'nama' => 'Korek', 'kategori' => 'Fasilitas Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0107', 'nama' => 'Set infus', 'kategori' => 'BHP Medis', 'stok' => 19],
            ['kode' => 'ITM-MED-0109', 'nama' => 'Laci', 'kategori' => 'Fasilitas Lab', 'stok' => 2],
            ['kode' => 'ITM-MED-0111', 'nama' => 'Surgical instrument kit', 'kategori' => 'Fasilitas Medis', 'stok' => 3],
            ['kode' => 'ITM-MED-0112', 'nama' => 'Blood set', 'kategori' => 'BHP Medis', 'stok' => 5],
            ['kode' => 'ITM-MED-0116', 'nama' => 'Penampung urin', 'kategori' => 'Fasilitas Medis', 'stok' => 4],
            ['kode' => 'ITM-MED-0117', 'nama' => 'Selang kateter', 'kategori' => 'BHP Medis', 'stok' => 5],
            ['kode' => 'ITM-MED-0121', 'nama' => 'Kapas utuh', 'kategori' => 'Fasilitas Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0122', 'nama' => 'Urine bag', 'kategori' => 'BHP Medis', 'stok' => 10],
            ['kode' => 'ITM-MED-0125', 'nama' => 'Cairan spirtus', 'kategori' => 'Alat Laboratorium', 'stok' => 1],
            ['kode' => 'ITM-MED-0126', 'nama' => 'Matras hitam', 'kategori' => 'Fasilitas Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0127', 'nama' => 'Double spike', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0132', 'nama' => 'Mix 2 vial', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0134', 'nama' => 'Handuk goodmorning', 'kategori' => 'Fasilitas Lab', 'stok' => 4],
            ['kode' => 'ITM-MED-0137', 'nama' => 'Handsinitizer besar', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0141', 'nama' => 'Besi putih', 'kategori' => 'Fasilitas Medis', 'stok' => 2],
            ['kode' => 'ITM-MED-0142', 'nama' => 'Benedict reagen botol besar', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0146', 'nama' => 'Paperbag', 'kategori' => 'Fasilitas Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0147', 'nama' => 'Benedict botol kecil', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0148', 'nama' => 'Sarung bantal', 'kategori' => 'Fasilitas Lab', 'stok' => 8],
            ['kode' => 'ITM-MED-0149', 'nama' => 'Sarung kaki bayi', 'kategori' => 'Alat Medis', 'stok' => 5],
            ['kode' => 'ITM-MED-0152', 'nama' => 'Asam asetat', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0153', 'nama' => 'Sarung guling', 'kategori' => 'Alat Medis', 'stok' => 8],
            ['kode' => 'ITM-MED-0157', 'nama' => 'Baclyn', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0158', 'nama' => 'Celana dalam ibu', 'kategori' => 'Fasilitas Lab', 'stok' => 5],
            ['kode' => 'ITM-MED-0160', 'nama' => 'Tas hitam', 'kategori' => 'Fasilitas Medis', 'stok' => 6],
            ['kode' => 'ITM-MED-0162', 'nama' => 'Celana bayi', 'kategori' => 'Fasilitas Lab', 'stok' => 3],
            ['kode' => 'ITM-MED-0164', 'nama' => 'Hanscoon', 'kategori' => 'Fasilitas Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0165', 'nama' => 'Bedak', 'kategori' => 'BHP Medis', 'stok' => 2],
            ['kode' => 'ITM-MED-0166', 'nama' => 'Baju bayi', 'kategori' => 'Fasilitas Lab', 'stok' => 13],
            ['kode' => 'ITM-MED-0169', 'nama' => 'Pembalut', 'kategori' => 'BHP Medis', 'stok' => 5],
            ['kode' => 'ITM-MED-0170', 'nama' => 'Popok', 'kategori' => 'Alat Medis', 'stok' => 9],
            ['kode' => 'ITM-MED-0172', 'nama' => 'Bantal', 'kategori' => 'Fasilitas Lab', 'stok' => 3],
            ['kode' => 'ITM-MED-0173', 'nama' => 'Jelly', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0177', 'nama' => 'Handwash', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0178', 'nama' => 'Duck putih', 'kategori' => 'Alat Medis', 'stok' => 8],
            ['kode' => 'ITM-MED-0181', 'nama' => 'Kondom kateter', 'kategori' => 'BHP Medis', 'stok' => 5],
            ['kode' => 'ITM-MED-0182', 'nama' => 'Duck hijau', 'kategori' => 'Alat Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0183', 'nama' => 'Standar infus', 'kategori' => 'Fasilitas Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0184', 'nama' => 'NGT selang', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0188', 'nama' => 'Kain hijau', 'kategori' => 'Fasilitas Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0189', 'nama' => 'DPT combo', 'kategori' => 'BHP Medis', 'stok' => 12],
            ['kode' => 'ITM-MED-0190', 'nama' => 'Underpad', 'kategori' => 'Alat Medis', 'stok' => 15],
            ['kode' => 'ITM-MED-0191', 'nama' => 'IPV', 'kategori' => 'BHP Medis', 'stok' => 4],
            ['kode' => 'ITM-MED-0193', 'nama' => 'Polio oral', 'kategori' => 'BHP Medis', 'stok' => 3],
            ['kode' => 'ITM-MED-0195', 'nama' => 'MR', 'kategori' => 'BHP Medis', 'stok' => 10],
            ['kode' => 'ITM-MED-0197', 'nama' => 'BCG', 'kategori' => 'BHP Medis', 'stok' => 4],
            ['kode' => 'ITM-MED-0199', 'nama' => 'pvc', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0200', 'nama' => 'Termo airaksa', 'kategori' => 'Fasilitas Lab', 'stok' => 3],
            ['kode' => 'ITM-MED-0201', 'nama' => 'HB 0', 'kategori' => 'BHP Medis', 'stok' => 5],
            ['kode' => 'ITM-MED-0203', 'nama' => 'Pelarut MR', 'kategori' => 'BHP Medis', 'stok' => 10],
            ['kode' => 'ITM-MED-0205', 'nama' => 'Spuit 1DUS 0,05', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0207', 'nama' => 'HBSAG', 'kategori' => 'BHP Medis', 'stok' => 9],
            ['kode' => 'ITM-MED-0210', 'nama' => 'Tisu', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0214', 'nama' => 'Alkohol swabs 1dus', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0216', 'nama' => 'Tespach', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0219', 'nama' => 'Handsaplas', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0222', 'nama' => 'Easytouch glukosa', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0224', 'nama' => 'Easytouch HB', 'kategori' => 'BHP Medis', 'stok' => 4],
            ['kode' => 'ITM-MED-0226', 'nama' => 'Kasa steril', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0228', 'nama' => 'IUD', 'kategori' => 'BHP Medis', 'stok' => 5],
            ['kode' => 'ITM-MED-0230', 'nama' => 'Botol kecil', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0232', 'nama' => 'Easytouch asam urat', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0234', 'nama' => 'Mikropor', 'kategori' => 'BHP Medis', 'stok' => 6],
            ['kode' => 'ITM-MED-0236', 'nama' => 'Hanscoon Panjang', 'kategori' => 'BHP Medis', 'stok' => 4],
            ['kode' => 'ITM-MED-0238', 'nama' => 'Kartu KB', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0240', 'nama' => 'Obat sub', 'kategori' => 'BHP Medis', 'stok' => 3],
            ['kode' => 'ITM-MED-0242', 'nama' => 'Tanda ibu hamil', 'kategori' => 'BHP Medis', 'stok' => 5],
            ['kode' => 'ITM-MED-0244', 'nama' => 'Kondom', 'kategori' => 'BHP Medis', 'stok' => 9],
            ['kode' => 'ITM-MED-0246', 'nama' => 'Kartu golongan darah', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0248', 'nama' => 'Sugical Brush', 'kategori' => 'BHP Medis', 'stok' => 3],
            ['kode' => 'ITM-MED-0250', 'nama' => 'Tisu gantung', 'kategori' => 'BHP Medis', 'stok' => 2],
            ['kode' => 'ITM-MED-0252', 'nama' => 'Lakmus', 'kategori' => 'BHP Medis', 'stok' => 10],
            ['kode' => 'ITM-MED-0254', 'nama' => 'Lancet', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0256', 'nama' => 'Obat diare (merit)', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0258', 'nama' => 'Jelly MY', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0259', 'nama' => 'Sepatu boots', 'kategori' => 'Fasilitas Lab', 'stok' => 2],
            ['kode' => 'ITM-MED-0260', 'nama' => 'Jelly venty', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0262', 'nama' => 'Kayu putih', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0264', 'nama' => 'Hansaplas anti septic', 'kategori' => 'BHP Medis', 'stok' => 2],
            ['kode' => 'ITM-MED-0266', 'nama' => 'Water for injection', 'kategori' => 'BHP Medis', 'stok' => 3],
            ['kode' => 'ITM-MED-0268', 'nama' => 'Betadine', 'kategori' => 'BHP Medis', 'stok' => 2],
            ['kode' => 'ITM-MED-0270', 'nama' => 'Baby oil', 'kategori' => 'BHP Medis', 'stok' => 3],
            ['kode' => 'ITM-MED-0272', 'nama' => 'Metergin', 'kategori' => 'BHP Medis', 'stok' => 4],
            ['kode' => 'ITM-MED-0274', 'nama' => 'Lidocaine', 'kategori' => 'BHP Medis', 'stok' => 4],
            ['kode' => 'ITM-MED-0275', 'nama' => 'Kom kapas', 'kategori' => 'Alat Medis', 'stok' => 8],
            ['kode' => 'ITM-MED-0277', 'nama' => 'Tutup kom kapas', 'kategori' => 'Alat Medis', 'stok' => 9],
            ['kode' => 'ITM-MED-0278', 'nama' => 'Vit K', 'kategori' => 'BHP Medis', 'stok' => 3],
            ['kode' => 'ITM-MED-0280', 'nama' => 'Microbion', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0282', 'nama' => 'Oksitosin', 'kategori' => 'BHP Medis', 'stok' => 4],
            ['kode' => 'ITM-MED-0284', 'nama' => 'Vit c', 'kategori' => 'BHP Medis', 'stok' => 3],
            ['kode' => 'ITM-MED-0286', 'nama' => 'Erian cetin', 'kategori' => 'BHP Medis', 'stok' => 2],
            ['kode' => 'ITM-MED-0288', 'nama' => 'Stampel', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0290', 'nama' => 'Aquabides', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0292', 'nama' => 'Gestin T1', 'kategori' => 'BHP Medis', 'stok' => 2],
            ['kode' => 'ITM-MED-0294', 'nama' => 'Andalan suntik KB', 'kategori' => 'BHP Medis', 'stok' => 2],
            ['kode' => 'ITM-MED-0296', 'nama' => 'Hair lotion', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0298', 'nama' => 'Toples plastic kecil', 'kategori' => 'BHP Medis', 'stok' => 2],
            ['kode' => 'ITM-MED-0300', 'nama' => 'Abocath putih', 'kategori' => 'BHP Medis', 'stok' => 4],
            ['kode' => 'ITM-MED-0303', 'nama' => 'Abocath hijau', 'kategori' => 'BHP Medis', 'stok' => 3],
            ['kode' => 'ITM-MED-0305', 'nama' => 'Abocath kuning', 'kategori' => 'BHP Medis', 'stok' => 2],
            ['kode' => 'ITM-MED-0307', 'nama' => 'Abocath ungu', 'kategori' => 'BHP Medis', 'stok' => 2],
            ['kode' => 'ITM-MED-0309', 'nama' => 'Abocath biru', 'kategori' => 'BHP Medis', 'stok' => 3],
            ['kode' => 'ITM-MED-0311', 'nama' => 'Singgle nidle', 'kategori' => 'BHP Medis', 'stok' => 7],
            ['kode' => 'ITM-MED-0313', 'nama' => 'Pct syirup', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0315', 'nama' => 'Ramolit', 'kategori' => 'BHP Medis', 'stok' => 5],
            ['kode' => 'ITM-MED-0317', 'nama' => 'Amolodipine', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0319', 'nama' => 'Nacl besar', 'kategori' => 'BHP Medis', 'stok' => 2],
            ['kode' => 'ITM-MED-0321', 'nama' => 'nacl kecil', 'kategori' => 'BHP Medis', 'stok' => 4],
            ['kode' => 'ITM-MED-0323', 'nama' => 'Dexrase', 'kategori' => 'BHP Medis', 'stok' => 2],
            ['kode' => 'ITM-MED-0325', 'nama' => 'Tablet tambah darah', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0327', 'nama' => 'Calcium lactate', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0329', 'nama' => 'Nesco lanaing delice', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0331', 'nama' => 'OMz', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0333', 'nama' => 'Pct tablet', 'kategori' => 'BHP Medis', 'stok' => 10],
            ['kode' => 'ITM-MED-0335', 'nama' => 'RL', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0337', 'nama' => 'Pispot', 'kategori' => 'Fasilitas Lab', 'stok' => 1],
            ['kode' => 'ITM-MED-0339', 'nama' => 'Mylanta', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0341', 'nama' => 'Remifitril', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0342', 'nama' => 'Mepenamil acid', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0343', 'nama' => 'Ondan', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0344', 'nama' => 'Intunal', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0345', 'nama' => 'Cooling spray S', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0346', 'nama' => 'Pispot BAB', 'kategori' => 'Fasilitas Lab', 'stok' => 1],
            ['kode' => 'ITM-MED-0348', 'nama' => 'Kapas', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0349', 'nama' => 'Kertas aba', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0350', 'nama' => 'kKapas iva tes', 'kategori' => 'BHP Medis', 'stok' => 11],
            ['kode' => 'ITM-MED-0351', 'nama' => 'Set tes darah', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0352', 'nama' => 'Kolestrol', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0353', 'nama' => 'phenenng', 'kategori' => 'BHP Medis', 'stok' => 22],
            ['kode' => 'ITM-MED-0354', 'nama' => 'Vaksimo sirup', 'kategori' => 'BHP Medis', 'stok' => 4],
            ['kode' => 'ITM-MED-0355', 'nama' => 'Farsifen', 'kategori' => 'BHP Medis', 'stok' => 4],
            ['kode' => 'ITM-MED-0356', 'nama' => 'Benang', 'kategori' => 'BHP Medis', 'stok' => 4],
            ['kode' => 'ITM-MED-0357', 'nama' => 'Jarum hecting', 'kategori' => 'BHP Medis', 'stok' => 5],
            ['kode' => 'ITM-MED-0358', 'nama' => 'Surgical blade', 'kategori' => 'BHP Medis', 'stok' => 5],
            ['kode' => 'ITM-MED-0359', 'nama' => 'Catgut', 'kategori' => 'BHP Medis', 'stok' => 7],
            ['kode' => 'ITM-MED-0361', 'nama' => 'kalsium', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0362', 'nama' => 'Ipi vit c', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0363', 'nama' => 'MGS04', 'kategori' => 'BHP Medis', 'stok' => 7],
            ['kode' => 'ITM-MED-0364', 'nama' => 'Mefenamid acid', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0365', 'nama' => 'PIL kb', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-MED-0366', 'nama' => 'HYpafid', 'kategori' => 'BHP Medis', 'stok' => 1],
            ['kode' => 'ITM-IT-0368', 'nama' => '40x kabel Jumper 20CM (20 M T M 20 F T F)', 'kategori' => 'Komponen Elektronik', 'stok' => 10],
            ['kode' => 'USBBA', 'nama' => 'Kabel USB tipe B to A', 'kategori' => 'Komponen Elektronik', 'stok' => 10],
            ['kode' => 'ITM-IT-0371', 'nama' => 'Header Pin  uk 8, 2, 10', 'kategori' => 'Komponen Elektronik', 'stok' => 10],
            ['kode' => 'ITM-IT-0372', 'nama' => 'LED 5MM', 'kategori' => 'Komponen Elektronik', 'stok' => 30],
            ['kode' => 'ITM-IT-0373', 'nama' => 'Resistor', 'kategori' => 'Komponen Elektronik', 'stok' => 30],
            ['kode' => 'PTM', 'nama' => 'Potensio Meter', 'kategori' => 'Komponen Elektronik', 'stok' => 10],
            ['kode' => 'PASBUZZ', 'nama' => 'Passive Buzzer', 'kategori' => 'Komponen Elektronik', 'stok' => 10],
            ['kode' => 'ITM-IT-0376', 'nama' => 'LED RGB', 'kategori' => 'Komponen Elektronik', 'stok' => 10],
            ['kode' => 'ITM-IT-0379', 'nama' => '3 Kabel Jumper F T M 20 CM', 'kategori' => 'Komponen Elektronik', 'stok' => 1],
            ['kode' => 'ITM-IT-0384', 'nama' => 'DVD tutorial', 'kategori' => 'Komponen Elektronik', 'stok' => 10],
            ['kode' => 'ITM-IT-0385', 'nama' => 'CAT Connector Plug', 'kategori' => 'Komponen Elektronik', 'stok' => 150],
            ['kode' => 'ITM-IT-0394', 'nama' => 'Kabel Micro HDMI (MICRO HDTV M/M', 'kategori' => 'Komponen Elektronik', 'stok' => 1],
            ['kode' => 'ITM-IT-0403', 'nama' => 'Baterai Holder', 'kategori' => 'Komponen Elektronik', 'stok' => 10],
            ['kode' => 'RESK01', 'nama' => 'Resistor 68 OHM 1/4 WATT TOLERANCE 1 %', 'kategori' => 'Komponen Elektronik', 'stok' => 160],
            ['kode' => 'MSKEY16', 'nama' => 'Membran Switch Keypad 4x4 16 Key', 'kategori' => 'Komponen Elektronik', 'stok' => 5],
            ['kode' => 'JMTM30', 'nama' => 'Kabel Jumper 30cm M to M', 'kategori' => 'Komponen Elektronik', 'stok' => 160],
            ['kode' => 'JFTM30', 'nama' => 'Kabel Jumper 30cm F to M', 'kategori' => 'Komponen Elektronik', 'stok' => 160],
            ['kode' => 'JFTF30', 'nama' => 'Kabel Jumper 30cm F to F', 'kategori' => 'Komponen Elektronik', 'stok' => 160],
            ['kode' => 'LED05 & LED03', 'nama' => '1 Set Lampu LED berisi 20LED 5mm 5 Warna & 20 LED 3mm 5 warna', 'kategori' => 'Komponen Elektronik', 'stok' => 4],
            ['kode' => 'OLEDM66', 'nama' => 'Oled Mini', 'kategori' => 'Komponen Elektronik', 'stok' => 1],
            ['kode' => 'JMTM20', 'nama' => 'Kabel Jumper 20 cm M to M, M to F, F to F', 'kategori' => 'Komponen Elektronik', 'stok' => 10],
            ['kode' => 'USBATM', 'nama' => 'Kabel USB Tipe A to Mini', 'kategori' => 'Komponen Elektronik', 'stok' => 1],
            ['kode' => 'RESK10', 'nama' => 'Resistor 220. 1k. 10k OHM', 'kategori' => 'Komponen Elektronik', 'stok' => 30],
            ['kode' => 'PTM-DUP', 'nama' => 'Potensiometer', 'kategori' => 'Komponen Elektronik', 'stok' => 1],
            ['kode' => 'ITM-IT-0449', 'nama' => 'Passive Buzzer & Active Buzzer', 'kategori' => 'Komponen Elektronik', 'stok' => 1],
            ['kode' => 'OLEDM66-DUP', 'nama' => 'OLED Mini 0,66mm', 'kategori' => 'Komponen Elektronik', 'stok' => 4],
            ['kode' => 'OLEDM91', 'nama' => 'OLED Mini 0,91 mm', 'kategori' => 'Komponen Elektronik', 'stok' => 4],
            ['kode' => 'ITM-IT-0465', 'nama' => 'Kabel USB', 'kategori' => 'Komponen Elektronik', 'stok' => 4],
            ['kode' => 'PTS-T11', 'nama' => 'Pinset Antistatic 3 In 1 Profess ional Anti-Static Tweezers Kit Repair Tool', 'kategori' => 'Komponen Elektronik', 'stok' => 4],
            ['kode' => 'PNS-EBH', 'nama' => 'Pinset Static Elbow Tweeze rs With Replacing Elbow Head', 'kategori' => 'Fasilitas Lab', 'stok' => 4],
            ['kode' => 'PNY-TH', 'nama' => 'Sedot timah  Sedot Timah Penyedot Timah Aluminium', 'kategori' => 'Komponen Elektronik', 'stok' => 4],
        ];

        foreach ($items as $item) {
            $lokasi = in_array($item['kategori'], ['Alat Laboratorium', 'Alat Medis', 'BHP Medis', 'Alat Suntik', 'Obat/Vaksin', 'Fasilitas Lab', 'Fasilitas Medis', 'KDK', 'Komunitas']) 
                      ? 'Lab Kebidanan & Biomedis' 
                      : 'Lab Komputer & Robotik';

            Item::create([
                'kode_barang' => $item['kode'],
                'nama_barang' => $item['nama'],
                'kategori' => $item['kategori'],
                'stok' => $item['stok'],
                'kondisi' => 'Baik',
                'lokasi' => $lokasi,
            ]);
        }
    }
}
